language: node_js
sudo: false
node_js:
  "node"

cache: npm

notifications:
  email:
    recipients:
      - capstone28seachange@gmail.com
    on_success: always
    on_failure: always

branches:
  only:
  - master
  - develop

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"
  region: $AWS_REGION 
  app: "SeaChange"
  env: "Seachange-env"
  bucket_name: $AWS_EB_BUCKET_NAME
  on:
    branch: develop

after_success:
- echo "Success!"

after_deploy:
  - echo "Finish deploying!"